create table Info (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	place VARCHAR(50)
);
insert into Info (id, first_name, last_name, place) values (1, 'Craggie', 'Clampton', 'Peru');
insert into Info (id, first_name, last_name, place) values (2, 'Aluin', 'Milan', 'Czech Republic');
insert into Info (id, first_name, last_name, place) values (3, 'Cass', 'Bortoli', 'Norway');
insert into Info (id, first_name, last_name, place) values (4, 'Emelina', 'Dugan', 'Czech Republic');
insert into Info (id, first_name, last_name, place) values (5, 'Jaquenetta', 'Dreng', 'Brazil');
insert into Info (id, first_name, last_name, place) values (6, 'Adolphus', 'Pedreschi', 'China');
insert into Info (id, first_name, last_name, place) values (7, 'Nathanial', 'Jessope', 'Australia');
insert into Info (id, first_name, last_name, place) values (8, 'Rafaela', 'Kynston', 'Yemen');
insert into Info (id, first_name, last_name, place) values (9, 'Derward', 'McComiskie', 'China');
insert into Info (id, first_name, last_name, place) values (10, 'Maxine', 'Mosey', 'Peru');
insert into Info (id, first_name, last_name, place) values (11, 'Chic', 'Grenshields', 'China');
insert into Info (id, first_name, last_name, place) values (12, 'Marianne', 'Rathmell', 'Belarus');
insert into Info (id, first_name, last_name, place) values (13, 'Dorothea', 'Kerin', 'Russia');
insert into Info (id, first_name, last_name, place) values (14, 'Noel', 'Veart', 'United States');
insert into Info (id, first_name, last_name, place) values (15, 'Sylvan', 'Varrow', 'France');
insert into Info (id, first_name, last_name, place) values (16, 'Tally', 'Kleinzweig', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (17, 'Clari', 'Young', 'Ecuador');
insert into Info (id, first_name, last_name, place) values (18, 'Teodoro', 'O''Fallowne', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (19, 'Laverna', 'Abate', 'China');
insert into Info (id, first_name, last_name, place) values (20, 'Clementius', 'Normington', 'Moldova');
insert into Info (id, first_name, last_name, place) values (21, 'Gilli', 'Empleton', 'China');
insert into Info (id, first_name, last_name, place) values (22, 'Orella', 'Freeborne', 'China');
insert into Info (id, first_name, last_name, place) values (23, 'Griffie', 'Wren', 'Portugal');
insert into Info (id, first_name, last_name, place) values (24, 'Obed', 'Pugh', 'East Timor');
insert into Info (id, first_name, last_name, place) values (25, 'Pietrek', 'Jenkyn', 'Mauritius');
insert into Info (id, first_name, last_name, place) values (26, 'Alexina', 'McIlharga', 'Yemen');
insert into Info (id, first_name, last_name, place) values (27, 'Idette', 'Piwall', 'Guatemala');
insert into Info (id, first_name, last_name, place) values (28, 'Madel', 'Youell', 'Sweden');
insert into Info (id, first_name, last_name, place) values (29, 'Vinny', 'McOrkill', 'Vietnam');
insert into Info (id, first_name, last_name, place) values (30, 'Morris', 'Moss', 'Philippines');
insert into Info (id, first_name, last_name, place) values (31, 'Valeda', 'Tipperton', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (32, 'Nicole', 'Girkins', 'Greece');
insert into Info (id, first_name, last_name, place) values (33, 'Aida', 'Avramovich', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (34, 'Felicia', 'Dafydd', 'Philippines');
insert into Info (id, first_name, last_name, place) values (35, 'Ricca', 'Tuminelli', 'Ivory Coast');
insert into Info (id, first_name, last_name, place) values (36, 'Waneta', 'Aleksashin', 'Norway');
insert into Info (id, first_name, last_name, place) values (37, 'Joyous', 'Daniellot', 'Canada');
insert into Info (id, first_name, last_name, place) values (38, 'Thorin', 'Arthurs', 'Croatia');
insert into Info (id, first_name, last_name, place) values (39, 'Rhys', 'Cornfield', 'Greece');
insert into Info (id, first_name, last_name, place) values (40, 'Delainey', 'Bedford', 'Belarus');
insert into Info (id, first_name, last_name, place) values (41, 'Nyssa', 'Pesek', 'Sweden');
insert into Info (id, first_name, last_name, place) values (42, 'Anthe', 'Alfonzo', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (43, 'Carolee', 'Essame', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (44, 'Ker', 'Doorbar', 'Sweden');
insert into Info (id, first_name, last_name, place) values (45, 'Giffy', 'MacGilpatrick', 'Montenegro');
insert into Info (id, first_name, last_name, place) values (46, 'Gardie', 'Laslett', 'Brazil');
insert into Info (id, first_name, last_name, place) values (47, 'Mariana', 'Bouda', 'China');
insert into Info (id, first_name, last_name, place) values (48, 'Humphrey', 'Spiller', 'Colombia');
insert into Info (id, first_name, last_name, place) values (49, 'Fran', 'Mannin', 'Palestinian Territory');
insert into Info (id, first_name, last_name, place) values (50, 'Carola', 'Brick', 'China');
insert into Info (id, first_name, last_name, place) values (51, 'Olga', 'Linscott', 'Colombia');
insert into Info (id, first_name, last_name, place) values (52, 'Demetre', 'Faulo', 'China');
insert into Info (id, first_name, last_name, place) values (53, 'Caralie', 'Osipov', 'Canada');
insert into Info (id, first_name, last_name, place) values (54, 'Juana', 'L'' Estrange', 'China');
insert into Info (id, first_name, last_name, place) values (55, 'Dannie', 'Pigden', 'China');
insert into Info (id, first_name, last_name, place) values (56, 'Hayden', 'Niset', 'Russia');
insert into Info (id, first_name, last_name, place) values (57, 'Sheridan', 'Roo', 'South Africa');
insert into Info (id, first_name, last_name, place) values (58, 'Staffard', 'Wiltshear', 'China');
insert into Info (id, first_name, last_name, place) values (59, 'Hilary', 'Redler', 'Colombia');
insert into Info (id, first_name, last_name, place) values (60, 'Martie', 'Wims', 'Sri Lanka');
insert into Info (id, first_name, last_name, place) values (61, 'Adaline', 'Van Vuuren', 'Greece');
insert into Info (id, first_name, last_name, place) values (62, 'Tersina', 'Mayston', 'Russia');
insert into Info (id, first_name, last_name, place) values (63, 'Vittoria', 'Hanton', 'China');
insert into Info (id, first_name, last_name, place) values (64, 'Remus', 'Kinglesyd', 'Nigeria');
insert into Info (id, first_name, last_name, place) values (65, 'Leora', 'Gonnelly', 'Canada');
insert into Info (id, first_name, last_name, place) values (66, 'Carlyn', 'Bortolussi', 'Sweden');
insert into Info (id, first_name, last_name, place) values (67, 'Yanaton', 'Lody', 'Russia');
insert into Info (id, first_name, last_name, place) values (68, 'Adolpho', 'Stear', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (69, 'Allys', 'Nealand', 'Poland');
insert into Info (id, first_name, last_name, place) values (70, 'Christie', 'Colleer', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (71, 'Edith', 'Ghilardini', 'China');
insert into Info (id, first_name, last_name, place) values (72, 'Almire', 'Eastlake', 'Ukraine');
insert into Info (id, first_name, last_name, place) values (73, 'Keenan', 'Karpfen', 'Portugal');
insert into Info (id, first_name, last_name, place) values (74, 'Carree', 'Stuehmeier', 'Sweden');
insert into Info (id, first_name, last_name, place) values (75, 'Petronille', 'Veltmann', 'Portugal');
insert into Info (id, first_name, last_name, place) values (76, 'Vi', 'Coetzee', 'China');
insert into Info (id, first_name, last_name, place) values (77, 'Gilburt', 'Maskelyne', 'Greece');
insert into Info (id, first_name, last_name, place) values (78, 'Marcille', 'Smee', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (79, 'Lamond', 'Banner', 'Malaysia');
insert into Info (id, first_name, last_name, place) values (80, 'Gauthier', 'Geere', 'Bolivia');
insert into Info (id, first_name, last_name, place) values (81, 'Hall', 'Flisher', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (82, 'Mehetabel', 'Esley', 'Thailand');
insert into Info (id, first_name, last_name, place) values (83, 'Rafi', 'Aleevy', 'Philippines');
insert into Info (id, first_name, last_name, place) values (84, 'Bethina', 'Newhouse', 'Philippines');
insert into Info (id, first_name, last_name, place) values (85, 'Clotilda', 'Fearnehough', 'New Zealand');
insert into Info (id, first_name, last_name, place) values (86, 'Regen', 'Spottiswoode', 'Indonesia');
insert into Info (id, first_name, last_name, place) values (87, 'Ward', 'Bonnet', 'Sweden');
insert into Info (id, first_name, last_name, place) values (88, 'Robinia', 'Seemmonds', 'Philippines');
insert into Info (id, first_name, last_name, place) values (89, 'Stacia', 'Shreve', 'Philippines');
insert into Info (id, first_name, last_name, place) values (90, 'Ashleigh', 'Leverette', 'Poland');
insert into Info (id, first_name, last_name, place) values (91, 'Prue', 'Bourges', 'France');
insert into Info (id, first_name, last_name, place) values (92, 'Angelina', 'Allingham', 'China');
insert into Info (id, first_name, last_name, place) values (93, 'Dawna', 'Sheehy', 'Poland');
insert into Info (id, first_name, last_name, place) values (94, 'Julian', 'Culp', 'Colombia');
insert into Info (id, first_name, last_name, place) values (95, 'Estel', 'Cutriss', 'Philippines');
insert into Info (id, first_name, last_name, place) values (96, 'Kaine', 'Abelov', 'France');
insert into Info (id, first_name, last_name, place) values (97, 'Frans', 'Butchart', 'Russia');
insert into Info (id, first_name, last_name, place) values (98, 'Iggy', 'Berkowitz', 'Canada');
insert into Info (id, first_name, last_name, place) values (99, 'Anderea', 'Dougan', 'Ukraine');
insert into Info (id, first_name, last_name, place) values (100, 'Sissie', 'Keppie', 'Mexico');
